# Generated by Django 5.0.3 on 2024-03-27 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panji', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
