# Generated by Django 5.0.3 on 2024-03-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panji', '0002_alter_about_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='category',
        ),
        migrations.RenameField(
            model_name='skills',
            old_name='skill_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='skills',
            name='skill_image',
            field=models.ImageField(blank=True, null=True, upload_to='skill/'),
        ),
        migrations.AddField(
            model_name='skills',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
