# Generated by Django 5.0.3 on 2024-03-28 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panji', '0003_remove_skills_category_rename_skill_name_skills_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='name',
        ),
    ]
