# Generated by Django 5.0.3 on 2024-03-28 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panji', '0004_remove_skills_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='updated',
        ),
    ]
